spring:
  application:
    name: job-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5433/job_scheduler
    username: postgres
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: db/migration

retry:
  base-delay-ms: 2000
  max-delay-ms: 600000

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG