spring:
  application:
    name: job-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5433/job_scheduler
    username: postgres
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: db/migration

scheduler:
  worker-id: ${HOSTNAME:worker-local}
  poll-interval-ms: 1000
  poll-batch-size: 20
  executor-pool-size: 8

retry:
  base-delay-ms: 2000
  max-delay-ms: 600000

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG